Sts.Role: arn:aws:iam::398099758646:role/Admin

Config.Repositories:
  dockerproductionaws/microtrader-base: {}
  dockerproductionaws/microtrader-audit: {}
  dockerproductionaws/microtrader-dashboard: {}
  dockerproductionaws/microtrader-portfolio: {}
  dockerproductionaws/microtrader-quote: {}
  dockerproductionaws/squid: {}
  dockerproductionaws/codebuild:
    ReadOnlyServices:
      - codebuild.amazonaws.com
